In [1]:
import numpy as np

In [7]:
taxi_data = np.genfromtxt('Taxi_dataset/nyc_taxis.csv', delimiter=',', skip_header = True)

In [10]:
taxi_data.shape

(89560, 15)

In [11]:
taxi_data.shape[0] # total number of riders

89560

In [13]:
print(taxi_data)

[[2.016e+03 1.000e+00 1.000e+00 ... 1.165e+01 6.999e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 8.000e+00 5.430e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 0.000e+00 3.780e+01 2.000e+00]
 ...
 [2.016e+03 6.000e+00 3.000e+01 ... 5.000e+00 6.334e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 8.950e+00 4.475e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 0.000e+00 5.484e+01 2.000e+00]]


In [14]:
taxi_data.size

1343400

In [15]:
taxi_data.dtype

dtype('float64')

In [16]:
taxi_data[:, 12]

array([11.65,  8.  ,  0.  , ...,  5.  ,  8.95,  0.  ])

In [18]:
round(taxi_data[:, 12].mean(), 2)

5.81

In [20]:
"{:.2f}".format(taxi_data[:, 12].mean())

'5.81'

In [26]:
tip_amount = taxi_data[:, 12]

In [27]:
fifty = tip_amount > 50

In [28]:
tip_amount[fifty]

array([ 52.8 ,  60.  ,  59.34,  80.  ,  70.  ,  60.  ,  55.  ,  65.  ,
        80.  ,  62.  , 100.  ,  58.  ,  62.  ,  75.7 ,  60.  ,  70.  ])

In [29]:
online_payments = taxi_data[:, -1] == 1

In [30]:
online_payments.sum()

64356

In [31]:
cash_payments = taxi_data[:, -1] == 2

In [32]:
cash_payments.sum()

24520

In [33]:
taxi_data[:, 7].max()

182.9

In [36]:
max_distance = taxi_data[:, 7]
maximum_distance = max(max_distance)
index_of = np.where(max_distance == 182.9)
fare_amount = taxi_data[:,9]
fare_amount[index_of]

array([2.5])